version: "3.8"
services:
  db:
    container_name: psql_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: otp_database
    ports:
      - "8432:5432"
